version: '3.4'
name: store-microsservices
services:

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch
  # kibana:
  #    image: docker.elastic.co/kibana/kibana

  portainer:
    image: portainer/portainer-ce

  pgadmin:
    image: dpage/pgadmin4

  mongodb:
    image: mongo

  redisdb:
    image: redis:alpine

  postgresdb:
    image: postgres

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.mvc:
    image: ${DOCKER_REGISTRY-}identitymvc
    build:
      context: ../src
      dockerfile: Services/Identity/Identity.MVC/Dockerfile

  register.api:
    image: ${DOCKER_REGISTRY-}registerapi
    build:
        context: ../src
        dockerfile: Services/Register/Register.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ../src
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ../src
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: ../src
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: ../src
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: ../src
      dockerfile: Services/Order/Order.API/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: ../src
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: ../src
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile

  aspnetrazor:
    image: ${DOCKER_REGISTRY-}aspnetrazor
    build:
      context: ../src
      dockerfile: WebApps/AspNetRazor/Dockerfile

  aspnetcoremvc:
    image: ${DOCKER_REGISTRY-}aspnetcoremvc
    build:
      context: ../src
      dockerfile: WebApps/AspNetCoreMVC/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  portainer_data:
  pgadmin_data:
  elasticsearch-data:
